const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/api.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "An API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3003",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Makers",
            "description": "Endpoints"
        },
        {
            "name": "Vendors",
            "description": "Endpoints"
        },
        {
            "name": "Categories",
            "description": "Endpoints"
        },
        {
            "name": "Sales",
            "description": "Endpoints"
        },
        {
            "name": "Purchases",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
  
    },
    definitions: {
        Maker: {
            "id": 1,
            "name": "acme-maker",
            "display_name": "ACME Maker",
            "instagram": "acmemaker"
        },
        MakerAdd: {
            "status": "OK",
            "makerId": 1
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})